---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: reload prometheus
  uri:
    url: "http://localhost:{{ prometheus_port }}/-/reload"
    method: POST
    status_code: [200, 204]
  ignore_errors: yes
