---
env: staging
eks_cluster_name: jc-staging-eks-staging

hub_monitoring_ip: "10.58.29.83"
hub_jaeger_endpoint: "{{ hub_monitoring_ip }}:4317"

node_exporter_enabled: true
kube_state_metrics_enabled: true
otel_collector_enabled: true
